name: Profile Stats
on:
  schedule:
    - cron: "5 11 * * *"
  workflow_dispatch:
  workflow_run:
    workflows: ["WakaTime Stats"]
    types:
      - completed

jobs:
  update-stats:
    name: Update Profile Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install

      - name: Generate Stats
        env:
          GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}
        run: bun generate-stats.js

      - name: Commit Changes
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add README.md
          if [[ "$(git status --porcelain)" != "" ]]; then
            git commit -m "Update profile stats"
            git push
          fi
