name: WakaTime Stats
on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

jobs:
  update-waka:
    name: Update WakaTime
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Update WakaTime Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: all_time
          IGNORED_LANGUAGES: "Binary YAML JSON TOML Other jsonc"
          SHOW_TITLE: true
          BLOCKS: "⣀⣄⣤⣦⣶⣷⣿"
          SHOW_TOTAL: true
          LANG_COUNT: 10
          COMMIT_MESSAGE: "Update WakaTime stats"
